version: '3.8'
services:
  database:
    container_name: postgres_database
    image: postgres:13
    ports: 
    - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwordpw
      POSTGRES_DB: postgresdb